services:
  - type: web
    name: treehole-web-blueprint
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn treehole.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: treehole-web-blueprint.onrender.com,glyz-team.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://treehole-web-blueprint.onrender.com,https://glyz-team.onrender.com
      - key: DJANGO_DEBUG
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: ALLOWED_EMAIL_DOMAINS
        value: yale.edu
      - key: DATABASE_URL
        fromDatabase:
          name: treehole-db-blueprint
          property: connectionString
    autoDeploy: true
databases:
  - name: treehole-db-blueprint
    plan: free

