services:
  - type: web
    name: glyz-team
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn treehole.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: glyz-team.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://glyz-team.onrender.com
      - key: DJANGO_DEBUG
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: ALLOWED_EMAIL_DOMAINS
        value: yale.edu
      - key: DATABASE_URL
        fromDatabase:
          name: glyz-team-db
          property: connectionString
    autoDeploy: true
databases:
  - name: glyz-team-db
    plan: free

